default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  host: 127.0.0.1

development:
  <<: *default
  database: todo_dev

test:
  <<: *default
  database: todo_test

production:
  <<: *default
  database: todo
  username: <%= ENV['DB_UN'] %>
  password: <%= ENV['DB_PW'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>